services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - sqlite
    environment:
      - DB_HOST=sqlite
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_NAME=gojek

  sqlite:
    image: sqlite
    volumes:
      - ./data:/data
    ports:
      - 3306:3306

volumes:
  mongodb_data:
